
apiVersion: v1
kind: Config
preferences: {}

clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJSi9EVk5kODZhRDR3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBME1qRXhNekk0TWpSYUZ3MHpOakEwTVRneE16TXpNalJhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUNtK0NPUDltamlpWFpaczhhQlBMN3JwOGV6cDM3N0dwT0U2cVZJcU9YdFB2aFFKckttWU9vOHd1Z2sKZXV5RU1RV3lqa1BmNVZjdkhHQUVWQ2lJNmNBb205OUUwSmE1SXd0c0NITHNzSDBLNUg2SnBOakNPMVljbFl2dApWbnEzaWt2Uk0xaCs5c2s1blJZWFhRdEZIeVBxS3JnTFpCaGx1V2xKUkNFc2VlUGFpNXVXU0U3VVM4YitxUjdKCllYYjNkZXZSTzFqeXpSZEY5YnNWZmVuRkNqODNrenA3eDlvZnZ1dy9ndkxTMGRDanU3QkVXMi9sUGRDQjRISmQKbjhzaERsYTdJb083Y2xNQkg5dzZjWDBSOWFGV0VCMWdpMG5xa1oyaGd4K0lZL2tCWkpMN05pY01WTEo1OVVhUQpPeTFsNFc2L2s3TWpvaUFCOWhtcjVKTzNyVUp4QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJUa3pPckVKaWtOcVR2dWxEN1RVYllkbStHdkFqQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQlp6L0ZQaEhXRwpiVElPb2VZOWdha2V5MEtXK1JqVkNGd2hQSW1hK2pwQTlmUEFVNG5rQ29rTURrZmpSclFNWUtOSWhzWU9GY1p4Cm5Bcmk4NzRLL241MHNyVkNSYUxDREFmOVhzWUNzMnNzZjBuZ3Y0UUlQUWEveXB2T0h2cjdCTWxPRFdRS0xrc2cKS084cFY5cG5sVlFLS2xtK2ZRWDVDUkVLZGNKWnFFbjV0L1FtOXlIN0lENGkrdDBEdnoveGV6Y1pORW0wcTcvcgpaSWtqc2grSXdqdGt3UmQ4Qi92M0FJRVc0TTlsOEk0QW5Gd3ZYRWNXN0pBUDZMNXpUeGdhY1NTYWI4RHNXWnNYCk1rN2IwSzJoU01URy91eDg1YmdpempkQlFhVjV1UlMxNWRPMWg4RHFhMGJTWFVDbzdsNm54czdpSjBDb1grcTUKaSsrM214UzJlRTc1Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://a2fbd44e-1dab-4205-af8c-7f94b3fa7dd2.ap-south-2-gw.linodelke.net:443
  name: lke594983

users:
- name: lke594983-admin
  user:
    as-user-extra: {}
    token: eyJhbGciOiJSUzI1NiIsImtpZCI6IjJpQjN0bDhlclZoV0VFYjJlZzRzbDUyeDZxZEkwazVUekxXQ0NMZGl0dWcifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJsa2UtYWRtaW4tdG9rZW4tbHJuZDgiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoibGtlLWFkbWluIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQudWlkIjoiYTE4YmIxNzQtMzE4My00ZjlkLWE2ZTctZTYyMGVhMWNhMDgxIiwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50Omt1YmUtc3lzdGVtOmxrZS1hZG1pbiJ9.reEj49EYPiM-DDyLA0kqnEfBhuiQsKxtOBdmSS_QzxPWBNmKmSDJ4U-7a2XIMvUxs7WqWEmUNaTvtbc5qLcCAR4a-2ozZulmqXIDYpvjFo3s3cWOtMefSkeG0e9wC_RINyUahLUd-uJnzo3Q8ze3b4ZxvBcjb4X6nX7ofadh3b-WFkKX2YrEqf6wjMLEsbMSuWmYeePEEyY0v-Y1EVg5NcRzI7pRJFQbqG7RlranKEDIw4qpZn7TXROBbmIxG9ud2bQDMoWioQ1v2YWOgGIKUXHMvIuCY8oETQi8jhV6EySdW-rVMMcoULSSEZx1NIcGe1MABK6E7Sj8db2g5Lkoqw

contexts:
- context:
    cluster: lke594983
    namespace: default
    user: lke594983-admin
  name: lke594983-ctx

current-context: lke594983-ctx
